style: pre-commit linter

diff --git a/backend/.pre-commit-config.yaml b/backend/.pre-commit-config.yaml
--- a/backend/.pre-commit-config.yaml
+++ b/backend/.pre-commit-config.yaml
@@ -25,7 +25,19 @@ repos:
     hooks:
       - id: check-branch-name
         name: Check branch name
-        entry: bash -c '[[ "$(git rev-parse --abbrev-ref HEAD)" =~ ^MTB-[0-9]+[A-Za-z0-9-]*$
-          ]] || (echo "Invalid branch name"; exit 1)'
+        entry: bash -c '
+          [[ "$(git rev-parse --abbrev-ref HEAD)" =~ ^MTB-[0-9]+[A-Za-z0-9-]*$ ]]
+          || (echo "Invalid branch name"; exit 1)'
         language: system
-        stages: [pre-commit]  # Явно указываем стадию
+        stages: [ pre-commit ]  # Явно указываем стадию
+      - id: fix-migrations-permissions
+        name: Fix migrations permissions
+        entry: >
+          bash -c '
+          if [ -d "backend/migrations" ]; then
+            find backend/migrations/ -type f -name "*.py" -exec chmod 664 {} \;
+            find backend/migrations/ -type d -exec chmod 775 {} \;
+          fi'
+        language: system
+        pass_filenames: false
+        stages: [ pre-commit ]
