MTB-5: added linter and changed logging

diff --git a/.github/workflows/backend-ci.yaml b/.github/workflows/backend-ci.yaml
--- a/.github/workflows/backend-ci.yaml
+++ b/.github/workflows/backend-ci.yaml
@@ -1,21 +1,93 @@
-name: Backend Tests
+name: Backend CI
 
 on:
   push:
     branches:
       - main
+    paths:
+      - 'backend/**'
   pull_request:
     branches:
       - main
       - 'MTB-*'
+    paths:
+      - 'backend/**'
 
 jobs:
+  # -------------------------------
+  # 1. linter
+  # ----------------------------
+  check-branch:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: backend
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
+
+      - name: Install Poetry
+        run: pip install poetry
+
+      - name: Install dev dependencies
+        run: poetry install --with dev
+
+      - name: Check branch name
+        run: |
+          BRANCH=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" | sed 's|refs/heads/||')
+          if [[ ! "$BRANCH" =~ ^MTB-[0-9]+[A-Za-z0-9-]*$ ]]; then
+            echo "Invalid branch name: $BRANCH. Must match MTB-<число><буквы/цифры/->"
+            exit 1
+          fi
+  # -------------------------------
+  # 1. linter
+  # ----------------------------
+  lint:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: backend
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
+
+      - name: Install Poetry
+        run: pip install poetry
+
+      - name: Cache Poetry dependencies
+        uses: actions/cache@v4
+        with:
+          path: ~/.cache/pypoetry
+          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
+          restore-keys: ${{ runner.os }}-poetry-
+
+      - name: Install dev dependencies
+        run: poetry install --with dev  # ruff, black, mypy и пр.
+
+      - name: Run Ruff
+        run: poetry run ruff check .
+
+      - name: Run Black
+        run: poetry run black --check .
+
+      - name: Run MyPy
+        run: poetry run mypy app
 
   # -------------------------------
   # 1. Unit tests
   # ----------------------------
   unit-tests:
     runs-on: ubuntu-latest
+    needs: lint
     defaults:
       run:
         working-directory: backend
@@ -49,6 +121,7 @@ jobs:
   # -------------------------------
   integration-tests:
     runs-on: ubuntu-latest
+    needs: unit-tests
     defaults:
       run:
         working-directory: backend
