MTB-5: added linter, changed logging, fixed tests after changed
* MTB-5: added linter and changed logging

* MTB-5: fixed linter

* MTB-5: fixed ci ruf

* MTB-5: fixed ci ruf

* MTB-5: fixed ci ruf

* MTB-5: fixed ci ruf

* MTB-5: fixed ci ruf

* MTB-5: fixed ci ruf

* MTB-5: fixed ci linter yaml

* MTB-5: fixed ci linter yaml

* MTB-5: fixed ci linter yaml

* MTB-5: fixed ci linter yaml

* MTB-5: fixed ci linter yaml

* MTB-5: fixed ci linter yaml

* MTB-5: fixed linter

* MTB-5: fixed linter

* MTB-5: fixed linter

* MTB-5: fixed linter

* MTB-5: fixed linter

* MTB-5: fixed tests after linter

* MTB-5: fixed tests after linter

diff --git a/.github/workflows/backend-ci.yaml b/.github/workflows/backend-ci.yaml
--- a/.github/workflows/backend-ci.yaml
+++ b/.github/workflows/backend-ci.yaml
@@ -1,4 +1,5 @@
-name: Backend Tests
+---
+name: Backend CI
 
 on:
   push:
@@ -10,12 +11,72 @@ on:
       - 'MTB-*'
 
 jobs:
+  yaml-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Lint YAML files
+        run: yamllint . --strict
+  # -------------------------------
+  # 1. check branch name
+  # ----------------------------
+  check-branch:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: backend
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check branch name
+        run: |
+          BRANCH=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" |
+          sed 's|refs/heads/||')
+          if [[ ! "$BRANCH" =~ ^MTB-[0-9]+[A-Za-z0-9-]*$ ]]; then
+            echo "Invalid branch name: $BRANCH.
+          Must match MTB-<numbers><letters/numbers/dashs/->"
+            exit 1
+          fi
+  # -------------------------------
+  # 1. linter
+  # ----------------------------
+  lint:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: backend
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
+      - name: Install Poetry
+        run: pip install poetry
+      - name: Cache Poetry dependencies
+        uses: actions/cache@v4
+        with:
+          path: ~/.cache/pypoetry
+          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
+          restore-keys: ${{ runner.os }}-poetry-
+      - name: Install dev dependencies
+        run: poetry install --no-root --with dev
+      - name: Run Ruff
+        uses: astral-sh/ruff-action@v3
+        with:
+          args: "check ."
+          src: "."
+      - name: Run Black
+        run: poetry run black --check .
+      - name: Run MyPy
+        run: poetry run mypy --explicit-package-bases app
 
   # -------------------------------
   # 1. Unit tests
   # ----------------------------
   unit-tests:
     runs-on: ubuntu-latest
+    needs: lint
     defaults:
       run:
         working-directory: backend
@@ -49,6 +110,7 @@ jobs:
   # -------------------------------
   integration-tests:
     runs-on: ubuntu-latest
+    needs: unit-tests
     defaults:
       run:
         working-directory: backend
@@ -80,9 +142,6 @@ jobs:
 
       - name: Install Poetry
         run: pip install poetry
-
-      - name: Install dependencies
-        run: poetry install
 
       - name: Cache Poetry dependencies
         uses: actions/cache@v4
